/**
 * Custom ImageModelV3 implementation for FLUX.2-dev via HuggingFace Gradio API.
 *
 * This wraps the black-forest-labs/FLUX.2-dev Space on HuggingFace
 * and exposes it as a standard AI SDK image model, usable with `generateImage()`.
 */
import type {
  ImageModelV3,
  ImageModelV3CallOptions,
  SharedV3Warning,
} from "@ai-sdk/provider";

export interface FluxModelConfig {
  /** HuggingFace Space ID (default: "black-forest-labs/FLUX.2-dev") */
  spaceId?: string;
  /** Default inference steps (default: 30) */
  defaultSteps?: number;
  /** Default guidance scale (default: 4) */
  defaultGuidanceScale?: number;
  /** Enable prompt upsampling (default: true) */
  promptUpsampling?: boolean;
  /** HuggingFace token for private/gated spaces */
  hfToken?: string;
}

/**
 * Creates a FLUX.2-dev image model compatible with AI SDK's `generateImage()`.
 *
 * @example
 * ```ts
 * import { generateImage } from "ai";
 * import { createFluxImageModel } from "@/lib/flux-image-model";
 *
 * const flux = createFluxImageModel();
 * const { image } = await generateImage({
 *   model: flux,
 *   prompt: "A futuristic cityscape at sunset",
 *   size: "1024x1024",
 * });
 * ```
 */
export function createFluxImageModel(
  config: FluxModelConfig = {}
): ImageModelV3 {
  const {
    spaceId = "black-forest-labs/FLUX.2-dev",
    defaultSteps = 30,
    defaultGuidanceScale = 4,
    promptUpsampling = true,
    hfToken,
  } = config;

  return {
    specificationVersion: "v3" as const,
    provider: "huggingface-flux",
    modelId: spaceId,
    maxImagesPerCall: 1, // FLUX generates one image per call

    async doGenerate(options: ImageModelV3CallOptions) {
      const warnings: SharedV3Warning[] = [];

      // Parse size from "{width}x{height}" format
      let width = 1024;
      let height = 1024;

      if (options.size) {
        const [w, h] = options.size.split("x").map(Number);
        if (w && h) {
          // Round to nearest multiple of 8 (FLUX requirement)
          width = Math.round(w / 8) * 8;
          height = Math.round(h / 8) * 8;
        }
      } else if (options.aspectRatio) {
        // Convert aspect ratio to dimensions, keeping one side at 1024
        const [aw, ah] = options.aspectRatio.split(":").map(Number);
        if (aw && ah) {
          if (aw >= ah) {
            width = 1024;
            height = Math.round((1024 * ah) / aw / 8) * 8;
          } else {
            height = 1024;
            width = Math.round((1024 * aw) / ah / 8) * 8;
          }
        }
      }

      // Warn about unsupported features
      if (options.n > 1) {
        warnings.push({
          type: "other",
          message:
            "FLUX.2-dev generates one image per call. Multiple images require multiple calls (handled by AI SDK).",
        });
      }

      const prompt = options.prompt ?? "";

      // Read provider-specific options
      const fluxOptions =
        (options.providerOptions?.["huggingface-flux"] as Record<
          string,
          unknown
        >) ?? {};
      const steps =
        (fluxOptions.num_inference_steps as number) ?? defaultSteps;
      const guidance =
        (fluxOptions.guidance_scale as number) ?? defaultGuidanceScale;
      const upsampling =
        (fluxOptions.prompt_upsampling as boolean) ?? promptUpsampling;

      // Dynamic import of Gradio client (ESM-only)
      const { Client } = await import("@gradio/client");

      const connectOptions: Record<string, unknown> = {};
      if (hfToken) {
        connectOptions.hf_token = hfToken;
      }

      const client = await Client.connect(spaceId, connectOptions);

      const result = await client.predict("/infer", {
        prompt,
        input_images: [],
        seed: options.seed ?? 0,
        randomize_seed: options.seed === undefined,
        width,
        height,
        num_inference_steps: steps,
        guidance_scale: guidance,
        prompt_upsampling: upsampling,
      });

      // Extract image data from Gradio response
      // Gradio Image components return either a URL string or a FileData object
      const data = result.data as unknown[];
      const imageData = data[0] as
        | string
        | { url: string; path?: string; orig_name?: string; mime_type?: string }
        | null;

      if (!imageData) {
        throw new Error("No image was generated by the FLUX model.");
      }

      let imageUrl: string;
      if (typeof imageData === "string") {
        imageUrl = imageData;
      } else if (imageData && typeof imageData === "object" && "url" in imageData) {
        imageUrl = imageData.url;
      } else {
        throw new Error(
          `Unexpected image response format from FLUX API: ${JSON.stringify(imageData)}`
        );
      }

      // Fetch the image binary data and convert to base64
      const imageResponse = await fetch(imageUrl);
      if (!imageResponse.ok) {
        throw new Error(
          `Failed to fetch generated image: ${imageResponse.status} ${imageResponse.statusText}`
        );
      }

      const arrayBuffer = await imageResponse.arrayBuffer();
      const base64 = Buffer.from(arrayBuffer).toString("base64");

      return {
        images: [base64],
        warnings,
        response: {
          timestamp: new Date(),
          modelId: spaceId,
          headers: undefined,
        },
      };
    },
  };
}
